[package]
name = "pliron-mlir-export"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Extensible Pliron to textual MLIR translation engine"
readme = "README.md"

[dependencies]
pliron = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pliron-derive = { workspace = true }
