; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 68c95415859a7e36a33ef490d00e2ffc072141526e17bd512456b260252a3d09.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare double @llvm.nvvm.rcp.rn.d(double)

define double @probe_rcp_rn_f64(double %arg0) {
  %result = call double @llvm.nvvm.rcp.rn.d(double %arg0)
  ret double %result
}
