; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 68c95415859a7e36a33ef490d00e2ffc072141526e17bd512456b260252a3d09.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define void @probe_tensormap_replace_global_dim(ptr %tensor_map, i32 %new_value) {
  call void asm sideeffect "tensormap.replace.tile.global_dim.global.b1024.b32 [$0], $1, $2;", "l,n,r,~{memory}"(ptr %tensor_map, i32 0, i32 %new_value)
  ret void
}
